### ISSUE TITLE
Wrapping the playground-api HTTP interface as a service

### ISSUE THREAD

**Issue by wangeguo** [amphitheatre-app/playground-react#8]
- [ ] Load files from Github Project https://github.com/amphitheatre-app/playground-api/issues/9
- [ ] Load files from Gists https://github.com/amphitheatre-app/playground-api/issues/10
- [ ] Synchronizing code to the server https://github.com/amphitheatre-app/playground-api/issues/11
- [ ] Returns execution results as SSE (Server-sent Events) https://github.com/amphitheatre-app/playground-api/issues/12

**Comment by onlyheartt9** [comment]
accept
